publicmarkup/legislation/urls.py
from django.conf.urls import patterns, url
from publicmarkup.legislation.feeds import LegislationComments
from publicmarkup.legislation.models import Legislation
from publicmarkup.legislation.views import Index, legislation_detail, legislation_print, title_detail, section_detail

feeds = {
    "comments": LegislationComments,
}

urlpatterns = patterns('',
    url(r'^$', Index.as_view(), name="index"),
    url(r'^bill/$', 'bill', name='bill'),
    url(r'^bill/(?P<legislation_slug>[-\w]+)/$', legislation_detail, name='legislation_detail'),
    url(r'^bill/(?P<legislation_slug>[-\w]+)/print/$', legislation_print, name='legislation_print'),
    url(r'^bill/(?P<legislation_slug>[-\w]+)/(?P<title_num>\d+)/$', title_detail, name='title_detail'),
    url(r'^bill/(?P<legislation_slug>[-\w]+)/(?P<title_num>\d+)/(?P<section_num>\d+)/$', section_detail, name='section_detail'),
    url(r'^feed/comments/$', LegislationComments()),
)

publicmarkup/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
from publicmarkup.legislation.views import Index

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^about/$', 'publicmarkup.views.about'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^comments/postfree/$','publicmarkup.legislation.views.save_free_comment'),
    url(r'^comments/', include('django.contrib.comments.urls')),
    url(r'^comments/', Index.as_view()),
    url(r'^contact/$', 'publicmarkup.views.contact'),
    url(r'^signup/$', 'publicmarkup.views.signup'),
    url(r'^', include('publicmarkup.legislation.urls')),
)

urlpatterns += patterns('django.contrib.auth.views',
    url(r'^login/$', 'login', {'template_name': 'login.html'}, name="login"),
    url(r'^logout/$', 'logout_then_login', name="logout"),
)

urls.py
from django.conf import settings
from django.conf.urls.defaults import *
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^about/$', 'publicmarkup.views.about'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^comments/postfree/$','publicmarkup.legislation.views.save_free_comment'),
    url(r'^comments/', include('django.contrib.comments.urls')),
    url(r'^comments/', 'publicmarkup.legislation.views.index'),
    url(r'^contact/$', 'publicmarkup.views.contact'),
    url(r'^signup/$', 'publicmarkup.views.signup'),
    url(r'^', include('mediasync.urls')),
    url(r'^', include('publicmarkup.legislation.urls')),
)

urlpatterns += patterns('django.contrib.auth.views',
    url(r'^login/$', 'login', {'template_name': 'login.html'}, name="login"),
    url(r'^logout/$', 'logout_then_login', name="logout"),
)

publicmarkup/legislation/models.py
from django.conf import settings
from django.contrib.comments.models import Comment
from django.db import models
import serpente

class Resource(models.Model):
    name = models.CharField(max_length=128, unique=True)
    value = models.TextField()
    def __unicode__(self):
        return self.name

class Legislation(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField()
    summary = models.TextField(blank=True, null=True)
    allow_comments = models.BooleanField(default=True)
    def get_absolute_url(self):
        return "/bill/%s/" % (self.slug)
    def get_sections_comment_count(self):
        sections = Section.objects.filter(title__legislation=self)
        section_ids = [section.id for section in sections]
        comment_count = Comment.objects.filter(object_pk__in=section_ids,
            content_type__app_label__exact="legislation",
            content_type__model__exact="section", site__id__exact=settings.SITE_ID).count()
        return comment_count
    def __unicode__(self):
        return self.name
    
class Title(models.Model):
    legislation = models.ForeignKey(Legislation, related_name="titles")
    number = models.IntegerField()
    name = models.CharField(max_length=255)
    summary = models.TextField(blank=True, null=True)
    extra_content = models.TextField(blank=True, null=True)
    class Meta:
        ordering = ['number','name']
    def roman_number(self):
        return serpente.encode(self.number)
    def get_absolute_url(self):
        return "/bill/%s/%i/" % (self.legislation.slug, self.number)
    def get_sections_comment_count(self):
        section_ids = [section.id for section in self.sections.all]
        comment_count = Comment.objects.filter(object_pk__in=section_ids,
            content_type__app_label__exact="legislation",
            content_type__model__exact="section", site__id__exact=settings.SITE_ID).count()
        return comment_count
    def __unicode__(self):
        return "TITLE %s - %s" % (self.roman_number(), self.name)

class Section(models.Model):
    title = models.ForeignKey(Title, related_name="sections")
    number = models.IntegerField()
    name = models.CharField(max_length=255)
    summary = models.TextField(blank=True, null=True)
    text = models.TextField()
    class Meta:
        ordering = ['number','name']
    def get_absolute_url(self):
        return "/bill/%s/%i/%i/" % (self.title.legislation.slug, self.title.number, self.number)
    def __unicode__(self):
        return "Sec. %i. %s" % (self.number, self.name)

publicmarkup/legislation/views.py
from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.contrib.comments.views.comments import post_comment
from django.http import Http404, HttpResponseRedirect, HttpResponseServerError
from django.shortcuts import render
from django.template import RequestContext
from django.views.generic import ListView
from humanity.forms import HumanityForm
from publicmarkup.legislation.models import Legislation, Title, Section

class Index(ListView):

    def get_queryset(self):
        return Legislation.objects.filter(allow_comments=False).order_by("-id")


def bill(request):
    legislation = Legislation.objects.order_by('-id')[0]
    return HttpResponseRedirect(legislation.get_absolute_url())


def legislation_print(request, legislation_slug):
    legislation = Legislation.objects.get(slug=legislation_slug)
    return render(request, "legislation/legislation_print.html", locals())


def legislation_detail(request, legislation_slug):

    try:
        legislation = Legislation.objects.get(slug=legislation_slug)
    except Legislation.DoesNotExist:
        return HttpResponseRedirect('/')

    if request.method == 'POST':
        human_form = HumanityForm(request.POST, label_suffix='')
        is_human = request.POST.get('humanity', 'robot') == 'human'
        if is_human or human_form.is_valid():
            return post_comment(request)
    else:
        human_form = HumanityForm(label_suffix='')

    data = {
        'legislation': legislation,
        'human_form': human_form,
    }

    return render(request, "legislation/legislation_detail.html", data)


def title_detail(request, legislation_slug, title_num):
    title = Title.objects.get(number=title_num, legislation__slug=legislation_slug)
    data = {
        'title': title,
        'legislation': title.legislation,
    }
    return render(request, "legislation/title_detail.html", data)


def section_detail(request, legislation_slug, title_num, section_num):

    if request.method == 'POST':
        human_form = HumanityForm(request.POST, label_suffix='')
        is_human = request.POST.get('humanity', 'robot') == 'human'
        if is_human or human_form.is_valid():
            return post_comment(request)
    else:
        human_form = HumanityForm(label_suffix='')

    section_num = int(section_num)
    section = Section.objects.get(number=section_num, title__number=title_num, title__legislation__slug=legislation_slug)
    try:
        next_section = Section.objects.get(number=section_num + 1, title__number=title_num, title__legislation__slug=legislation_slug)
    except Section.DoesNotExist:
        next_section = None
    try:
        previous_section = Section.objects.get(number=section_num - 1, title__number=title_num, title__legislation__slug=legislation_slug)
    except Section.DoesNotExist:
        previous_section = None
    data = {
        'legislation': section.title.legislation,
        'title': section.title,
        'section': section,
        'next_section': next_section,
        'previous_section': previous_section,
        'human_form': human_form,
    }
    return render(request, "legislation/section_detail.html", data)


def save_comment(request):
    if request.POST:
        human_form = HumanityForm(request.POST)
        if human_form.is_valid():
            return post_comment(request)
    else:
        raise Http404, "All you do is GET, GET, GET. How about you POST every once in a while like you used to at the beginning of our relationship?"


def save_free_comment(request):

    if request.POST:

        target = request.POST.get("target", None)

        if target:

            (ct_id, obj_id) = target.split(":")

            user_type = ContentType.objects.get(id=ct_id)

            if user_type.model == "section":
                section = Section.objects.get(pk=obj_id)
                legislation = section.title.legislation
            elif user_type.model == "legislation":
                legislation = Legislation.objects.get(pk=obj_id)
            else:
                legislation = None

            if legislation and legislation.allow_comments:

                return post_comment(request, extra_context)

            else:

                raise Http404, "Sorry, comments are not allowed on this legislation."

    else:

        raise Http404, "All you do is GET, GET, GET. How about you POST every once in a while like you used to at the beginning of our relationship?"

    return HttpResponseServerError("DENIED! Not really, something just broke.")

publicmarkup/views.py
from django import forms
from django.conf import settings
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from django.template import RequestContext
from postmark import PMMail
from publicmarkup.legislation.models import Legislation

class ContactForm(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()
    comment = forms.CharField(widget=forms.Textarea())

# views

def index(request):
    legislation = Legislation.objects.filter(allow_comments=True)
    return render_to_response("legislation/legislation_list.html",
                              {'legislation': legislation},
                              context_instance=RequestContext(request))

def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST, label_suffix="")
        if form.is_valid():
            data = form.cleaned_data
            mailmsg = PMMail(
                subject='[PublicMarkup.org] contact from %s' % data['name'],
                text_body='%s <%s>\n\n%s' % (data['name'], data['email'], data['comment']),
                sender=settings.POSTMARK_SENDER,
                to=settings.POSTMARK_SENDER,
                reply_to=data['email'],
            )
            mailmsg.send()
            messages.success(request, "Thanks for contacting us. We'll get back to you shortly.")
            return HttpResponseRedirect('/')
    else:
        form = ContactForm(label_suffix="")
    return render_to_response("contact.html", {'form': form}, context_instance=RequestContext(request))

def signup(request):
    messages.success(request, "Thanks for signing up and getting involved in the transparency effort!")
    return HttpResponseRedirect('/')

def about(request):
    legislation = Legislation.objects.filter(allow_comments=False).order_by("-pk")
    return render_to_response("about.html", {'legislation': legislation}, context_instance=RequestContext(request))

publicmarkup/templates/comments/form.html
{% load comments i18n %}

<form action="#comment-form" method="post" id="comment-form">
    {% csrf_token %}
    {% if next %}
        <input type="hidden" name="next" value="{{ next }}" />
    {% else %}
        {% if section %}
            <input type="hidden" name="next" value="{{ section.get_absolute_url }}#last_comment" />
        {% else %}
            <input type="hidden" name="next" value="{{ legislation.get_absolute_url }}#last_comment" />
        {% endif %}
    {% endif %}
    {% for field in form.hidden_fields %}
        {{ field }}
    {% endfor %}
    <ul>
        {% for field in form.visible_fields %}
            {% if field.errors %}{{ field.errors }}{% endif %}
            <li class="field_{{ field.name }}{% if field.errors %} error{% endif %}{% ifequal field.name "honeypot" %} hidden{% endifequal %}">
                {{ field.label_tag }}
                {{ field }}
            </li>
        {% endfor %}
            <li id="testForm">
                {{ human_form }}
            </li>
            <!--    
            <li id="previewBtn" class="buttonli">
                <button type="submit" name="preview" class="submit-preview">
                    <span>Preview</span>
                </button>
            </li>
            -->
            <li id="postBtn" class="buttonli">
                <button type="submit" name="post" class="submit-post">
                    <span>Post</span>
                </button>
            </li>    
    </ul>
    <div class="clear"></div>
</form>

publicmarkup/templates/comments/free_preview.html
{% extends "index.html" %}

{% block content %}
<div id="doc4" class="yui-t7">
		{% include "header.html" %}
<div id="bd">

<div class="yui-g">

<div id="preview_container">
<div id="preview_container_top">
<h2>Please review your comment before posting. <span class="small">(or you may edit the comment, below)</span></h2></div>
<div id="preview_content">

<form action="/comments/postfree/" method="post" id="free_comment_form">
	<input type="hidden" name="" value="true" id="post_type" />
	{% if comment_form.has_errors %}
	    <p><strong style="color: red;">Please correct the following errors.</strong></p>
	{% else %}
	    	<div class="comment" id="previewed_comment">
	    {{ comment.comment|escape|urlizetrunc:"40"|linebreaks }}
	    <p class="comment_attrib">Posted by <strong>{{ comment.person_name|escape }}</strong></p>
		 	</div>

	<div id="recaptcha_container">
	   <h2>You're almost finished!</h2><p>In an effort to prevent spam, we're using re-captcha.  
	   Simply type the two words you see to confirm that you are indeed a human.<br /> <small>
	   (If for some reason you do not see a red box below with space for 2 words to be typed, the "captcha" hasn't loaded. Click your browser's back button and attempt to preview your comment again.)
	   </small>
	   </p>

		{% autoescape off %}{{ recaptcha_html }}{% endautoescape %}</div>
	
	<div class="buttons" style="margin-left:1em; margin-top:2em;">
				<a href="#" class="new" id="free_comment_form_submit">
					Post Your Comment
				</a>
			</div>
	
	</div>

<!-- <input type="submit" name="post" value="Post public comment" class="preview_button" /> -->


<br />
</div> <!-- end preview content -->

	    
	{% endif %}


	<div id="preview_comment_box">
	
<div id="edit_comment_box"><h2>Care to edit your comment before posting?</h2>
	<a name="edit_comment"></a>
	

	<p class="field_headers">
		<label for="id_person_name">Your name (and Organization):</label>
		{% if comment_form.person_name.errors %}{{ comment_form.person_name.html_error_list }}{% endif %}
	</p>
	{{ comment_form.person_name }}
	<br />
	{% if comment_form.comment.errors %}
		{{ comment_form.comment.html_error_list }}
	{% endif %}

	
		<p class="field_headers"><label for="id_comment">Comment:</label>
		</p>
		{{ comment_form.comment }}
<br />
	
	<input type="hidden" name="options" value="{{ options }}" />
	<input type="hidden" name="target" value="{{ target }}" />
	<input type="hidden" name="gonzo" value="{{ hash }}" />


		<!-- 	<p><input type="submit" name="preview" value="Preview revised comment" />	</p>-->
		
	<div class="buttons" style="margin-top:2em;">
		<a href="#" class="new" id="free_comment_form_preview">
			Preview Revised Comment
		</a>
	</div>
	
</form>
<script type="text/javascript" charset="utf-8">
	Sunlight.Application.addLoadEvent(function() {
		if ($('free_comment_form_submit')) {
			$('free_comment_form_submit').onclick = function() {
				$('post_type').name = 'post';
				$('free_comment_form').submit();
				return false;
			};
		}
		if ($('free_comment_form_preview')) {
			$('free_comment_form_preview').onclick = function() {			
				var name = $('id_person_name');
				if (!name.value || name.value == "") {
					name.value = "Anonymous";
				}
				$('post_type').name = 'preview';
				$('free_comment_form').submit();
				return false;
			}
		};
	});
</script>


</div>		
	</div>    

</div> <!-- end preview_container -->

</div> <!-- end YUI g -->


{% include "footer.html" %}
	</div>

{% endblock %}

publicmarkup/templates/comments/freeform.html
{% if display_form %}

	<form action="/comments/postfree/" method="post" id="free_comment_form">
		<input type="hidden" name="preview" value="true" />
		<input type="hidden" name="options" value="{{ options }}" />
		<input type="hidden" name="target" value="{{ target }}" />
		<input type="hidden" name="gonzo" value="{{ hash }}" />
		<p class="field_headers">Your Name (and Organization*):</p>
		<input name="person_name" id="free_comment_form_name" size="40" />
		<p class="field_headers">Your Comment: <span class="comment_disclaimer_leg">(HTML is not permitted, but links will be automatically linked)</span></p>
		<textarea cols="70" rows="10" name="comment"></textarea>
		<div id="small_disclaimer">*We encourage you to take credit for your comments by including your name and organization.</div>
		<p>


			<div class="buttons">
				<a href="#" class="new" id="free_comment_form_submit">
					Preview Your Comment
				</a>
			</div>
			

		</p>
	</form>
	<script type="text/javascript" charset="utf-8">
		Sunlight.Application.addLoadEvent(function() {
			$('free_comment_form_submit').onclick = function() {
				var name = $('free_comment_form_name');
				if (!name.value || name.value == "") {
					name.value = "Anonymous";
				}
				$('free_comment_form').submit();
				return false;
			}
		});
	</script>
{% endif %}

publicmarkup/templates/comments/posted.html
{% extends "index.html" %}

{% block meta %}
<meta http-equiv="refresh" content="0;{{ object.get_absolute_url }}#latest-comment"/>
{% endblock %}

{% block content %}
<div id="doc4" class="yui-t7">
		{% include "header.html" %}
<div id="bd">

<div class="yui-g">
<div id="preview_container">
<div id="preview_container_top">
<h2>Comment posted successfully!</h2></div>
<div id="preview_content">

{% if object %}
<h4>Hold on... We're taking you to comment.</h4>
<p>Are you patient enough to wait for <a href="{{ object.get_absolute_url }}#latest-comment">the page</a>?</p>
{% endif %}

</div>
</div>
</div>


{% include "footer.html" %}
	</div>
{% endblock %}

publicmarkup/templates/comments/preview.html
{% extends "base.html" %}
{% load comments %}
{% load i18n %}

{% block title %}{% trans "Preview your comment" %}{% endblock %}

{% block content %}

    <h2>Sorry, we need you to change your comment.</h2>
    
    <div id="comment_box">
        <form action="#comment-form" method="post" id="comment-form">
            {% csrf_token %}
            {% if next %}<input type="hidden" name="next" value="{{ next }}" />{% endif %}
            <input type="hidden" name="humanity" value="human" />
            {% for field in form.hidden_fields %}
                {{ field }}
            {% endfor %}
            <ul>
                {% for field in form.visible_fields %}
                    {% if field.errors %}{{ field.errors }}{% endif %}
                    <li class="field_{{ field.name}}{% if field.errors %} error{% endif %}"{% ifequal field.name "honeypot" %} style="display:none;"{% endifequal %}>
                        {{ field.label_tag }}
                        {{ field }}
                    </li>
                {% endfor %}
                <li id="postBtn" class="buttonli">
                    <button type="submit" name="post" class="submit-post">
                        <span>Post</span>
                    </button>
                </li>
            </ul>   
        </form>
    </div>

{% endblock %}